spring.application.name=eat2day
# JSP 설정
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Oracle 설정
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xe
spring.datasource.username=scott
spring.datasource.password=tiger

# MyBatis 설정
mybatis.mapper-locations=classpath:mybatis/mapper/**/**.xml

# 파일업로드 설정
# 최대 파일 크기 설정 (기본값 : 1MB)
spring.servlet.multipart.max-file-size = 10MB
# 최대 요청 파일 크기 설정 (기본값 : 1MB)
spring.servlet.multipart.max-request-size = 10MB

# Elasticsearch 설정
spring.elasticsearch.uris=http://localhost:9200

server.servlet.encoding.charset=UTF-8
server.tomcat.uri-encoding=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

#gmail 설정
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=YOUR EMAIL
spring.mail.password=YOUR PASSWORD
spring.mail.protocol=smtp

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

logging.level.org.springframework.security=DEBUG



# 구글
spring.security.oauth2.client.registration.google.client-id=YOUR_GOOGLE_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=YOUR_GOOGLE_CLIENT_SECRET
spring.security.oauth2.client.registration.google.scope=email,profile

# =========================
# Kakao OAuth2 (Spring Security)
# =========================

spring.security.oauth2.client.registration.kakao.client-name=Kakao
spring.security.oauth2.client.registration.kakao.client-id=03ebc58c93495adf504f3d41ef3a526e
spring.security.oauth2.client.registration.kakao.client-secret=br0HtQVtnfgj6W2Od927NUcsZNTUAUP
spring.security.oauth2.client.registration.kakao.client-authentication-method=client_secret_post
spring.security.oauth2.client.registration.kakao.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.kakao.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

# 카카오에서 사용자 정보 받을 범위(원하는 것만)
spring.security.oauth2.client.registration.kakao.scope=profile_nickname

# Provider 설정
spring.security.oauth2.client.provider.kakao.authorization-uri=https://kauth.kakao.com/oauth/authorize
spring.security.oauth2.client.provider.kakao.token-uri=https://kauth.kakao.com/oauth/token
spring.security.oauth2.client.provider.kakao.user-info-uri=https://kapi.kakao.com/v2/user/me
spring.security.oauth2.client.provider.kakao.user-name-attribute=id



